---
- name: Display Banner
  ansible.builtin.debug:
      msg: "{{ lockdown_banner.split('\n') }}"
  tags:
      - always

- name: Gather Distribution Info
  ansible.builtin.setup:
      gather_subset: distribution,!all,!min
  when:
      - ansible_distribution is not defined
  tags:
      - always

- name: Check OS version and family
  ansible.builtin.assert:
      that:
          - ansible_os_family == 'Windows'
          - ansible_distribution | regex_search('(Microsoft Windows Server 2019)')
      success_msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }} is the detected operating system."
      fail_msg: "This role can only be run against Windows Server 2019 Editions. {{ ansible_distribution }} {{ ansible_distribution_major_version }} is not supported."
  tags:
      - always

- name: Check ansible version
  ansible.builtin.assert:
      that: ansible_version.full is version_compare(min_ansible_version, '>=')
      msg: You must use Ansible {{ min_ansible_version }} or greater
  tags:
      - always

- name: Include the preliminary tasks
  ansible.builtin.include_tasks: prelim.yml
  tags:
      - always
      - prelim_tasks

- name: Execute the section 1 tasks
  ansible.builtin.import_tasks: section01.yml
  when: win19cis_section01
  tags:
      - section01

- name: Execute the section 2 tasks
  ansible.builtin.import_tasks: section02.yml
  when: win19cis_section02
  tags:
      - section02

- name: Execute the section 5 tasks
  ansible.builtin.import_tasks: section05.yml
  when: win19cis_section05
  tags:
      - section05

- name: Execute the section 9 tasks
  ansible.builtin.import_tasks: section09.yml
  when: win19cis_section09
  tags:
      - section09

- name: Execute the section 17 tasks
  ansible.builtin.import_tasks: section17.yml
  when: win19cis_section17
  tags:
      - section17

- name: Execute the section 18 tasks
  ansible.builtin.import_tasks: section18.yml
  when: win19cis_section18
  tags:
      - section18

- name: Execute the section 19 tasks
  ansible.builtin.import_tasks: section19.yml
  when: win19cis_section19
  tags:
      - section19

- name: If Warnings found Output count and control IDs affected
  ansible.builtin.debug:
      msg:
          - "You have {{ warn_count }} Warning(s) that require investigation(s). Their IDâ€™s are listed below:"
          - "{{ warn_control_list }}"
  when: warn_count != 0
