---

- name: "9.1.1 | PATCH | Ensure 'Windows Firewall: Domain: Firewall state' is set to 'On (recommended)'"
  ansible.windows.win_regedit:
      path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\Domainprofile
      name: EnableFirewall
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.1.1
      - patch
      - firewall
      - domain

- name: "9.1.2 | PATCH | Ensure 'Windows Firewall: Domain: Inbound connections' is set to 'Block (default)'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile
      name: DefaultInboundAction
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.1.2
      - patch
      - firewall
      - domain

- name: "9.1.3 | PATCH | Ensure 'Windows Firewall: Domain: Outbound connections' is set to 'Allow (default)'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile
      name: DefaultOutboundAction
      data: 0
      type: dword
  when:
      - win19cis_rule_9_1_3
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.1.3
      - patch
      - firewall
      - domain

- name: "9.1.4 | PATCH | Ensure 'Windows Firewall: Domain: Settings: Display a notification' is set to 'No'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile
      name: DisableNotifications
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_4
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.1.4
      - patch
      - firewall
      - domain

# title has slashes switched
- name: "9.1.5 | PATCH | Ensure 'Windows Firewall: Domain: Logging: Name' is set to '%SystemRoot%/System32/logfiles/firewall/domainfw.log'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
      name: LogFilePath
      data: '{{ win19cis_domain_firewall_log_path }}'
      type: string
  when:
      - win19cis_rule_9_1_5
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.1.5
      - patch
      - firewall
      - domain

- name: "9.1.6 | PATCH | Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  block:
      - name: "9.1.6 | AUDIT | Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater'. | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have a invalid size set for win19cis_domain_firewall_log_size please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win19cis_domain_firewall_log_size < 16384

      - name: "9.1.6 | AUDIT | Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater' | Warn Count."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: '9.1.6'
        when:
            - win19cis_domain_firewall_log_size < 16384

      - name: "9.1.6 | PATCH | Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater' | Apply Settings To Registry."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
            name: LogFileSize
            data: '{{ win19cis_domain_firewall_log_size }}'
            type: dword
        when:
            - win19cis_domain_firewall_log_size >= 16384
  when:
      - win19cis_rule_9_1_6
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.1.6
      - patch
      - firewall
      - domain

- name: "9.1.7 | PATCH | Ensure 'Windows Firewall: Domain: Logging: Log dropped packets' is set to 'Yes'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
      name: LogDroppedPackets
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_7
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.1.7
      - patch
      - firewall
      - domain

- name: "9.1.8 | PATCH | Ensure 'Windows Firewall: Domain: Logging: Log successful connections' is set to 'Yes'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\DomainProfile\Logging
      name: LogSuccessfulConnections
      data: 1
      type: dword
  when:
      - win19cis_rule_9_1_8
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.1.7
      - patch
      - firewall
      - domain

- name: "9.2.1 | PATCH | Ensure 'Windows Firewall: Private: Firewall state' is set to 'On (recommended)'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile
      name: EnableFirewall
      data: 1
      type: dword
  when:
      - win19cis_rule_9_2_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.2.1
      - patch
      - firewall
      - private

- name: "9.2.2 | PATCH | Ensure 'Windows Firewall: Private: Inbound connections' is set to 'Block (default)'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile
      name: DefaultInboundAction
      data: 1
      type: dword
  when:
      - win19cis_rule_9_2_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.2.2
      - patch
      - firewall
      - private

- name: "9.2.3 | PATCH | Ensure 'Windows Firewall: Private: Outbound connections' is set to 'Allow (default)'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile
      name: DefaultOutboundAction
      data: 0
      type: dword
  when:
      - win19cis_rule_9_2_3
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.2.3
      - patch
      - firewall
      - private

- name: "9.2.4 | PATCH | Ensure 'Windows Firewall: Private: Settings: Display a notification' is set to 'No'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile
      name: DisableNotifications
      data: 1
      type: dword
  when:
      - win19cis_rule_9_2_4
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.2.4
      - patch
      - firewall
      - private

# title has slashes switched
- name: "9.2.5 | PATCH | Ensure 'Windows Firewall: Private: Logging: Name' is set to '%SystemRoot%/System32/logfiles/firewall/privatefw.log'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
      name: LogFilePath
      data: '{{ win19cis_private_firewall_log_path }}'
      type: string
  when:
      - win19cis_rule_9_2_5
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.2.5
      - patch
      - firewall
      - private

- name: "9.2.6 | PATCH | Ensure 'Windows Firewall: Private: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  block:
      - name: "9.2.6 | AUDIT | Ensure 'Windows Firewall: Private: Logging: Size limit (KB)' is set to '16,384 KB or greater' | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have a invalid size set for win19cis_private_firewall_log_size please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win19cis_private_firewall_log_size < 16384

      - name: "9.2.6 | AUDIT | Ensure 'Windows Firewall: Private: Logging: Size limit (KB)' is set to '16,384 KB or greater' | Warn Count."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: '9.2.6'
        when:
            - win19cis_private_firewall_log_size < 16384

      - name: "9.2.6 | PATCH | Ensure 'Windows Firewall: Private: Logging: Size limit (KB)' is set to '16,384 KB or greater' | Apply Settings To Registry."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
            name: LogFileSize
            data: '{{ win19cis_private_firewall_log_size }}'
            type: dword
        when:
            - win19cis_private_firewall_log_size >= 16384
  when:
      - win19cis_rule_9_2_6
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.2.6
      - patch
      - firewall
      - private

- name: "9.2.7 | PATCH | Ensure 'Windows Firewall: Private: Logging: Log dropped packets' is set to 'Yes'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
      name: LogDroppedPackets
      data: 1
      type: dword
  when:
      - win19cis_rule_9_2_7
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.2.7
      - patch
      - firewall
      - private

- name: "9.2.8 | PATCH | Ensure 'Windows Firewall: Private: Logging: Log successful connections' is set to 'Yes'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PrivateProfile\Logging
      name: LogSuccessfulConnections
      data: 1
      type: dword
  when:
      - win19cis_rule_9_2_8
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.2.8
      - patch
      - firewall
      - private

- name: "9.3.1 | PATCH | Ensure 'Windows Firewall: Public: Firewall state' is set to 'On (recommended)'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
      name: EnableFirewall
      data: 1
      type: dword
  when:
      - win19cis_rule_9_3_1
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.3.1
      - patch
      - firewall
      - public

- name: "9.3.2 | PATCH | Ensure 'Windows Firewall: Public: Inbound connections' is set to 'Block (default)'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
      name: DefaultInboundAction
      data: 1
      type: dword
  when:
      - win19cis_rule_9_3_2
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.3.2
      - patch
      - firewall
      - public

- name: "9.3.3 | PATCH | Ensure 'Windows Firewall: Public: Outbound connections' is set to 'Allow (default)'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
      name: DefaultOutboundAction
      data: 0
      type: dword
  when:
      - win19cis_rule_9_3_3
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.3.3
      - patch
      - firewall
      - public

- name: "9.3.4 | PATCH | Ensure 'Windows Firewall: Public: Settings: Display a notification' is set to 'No'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
      name: DisableNotifications
      data: 1
      type: dword
  when:
      - win19cis_rule_9_3_4
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.3.4
      - patch
      - firewall
      - public

- name: "9.3.5 | PATCH | Ensure 'Windows Firewall: Public: Settings: Apply local firewall rules' is set to 'No'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
      name: AllowLocalPolicyMerge
      data: 0
      type: dword
  when:
      - win19cis_rule_9_3_5
      - not win_skip_for_test
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.3.5
      - patch
      - firewall
      - public

- name: "9.3.6 | PATCH | Ensure 'Windows Firewall: Public: Settings: Apply local connection security rules' is set to 'No'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile
      name: AllowLocalIPsecPolicyMerge
      data: 0
      type: dword
  when:
      - win19cis_rule_9_3_6
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.3.6
      - patch
      - firewall
      - public

# title has slashes switched
- name: "9.3.7 | PATCH | Ensure 'Windows Firewall: Public: Logging: Name' is set to '%SystemRoot%/System32/logfiles/firewall/publicfw.log'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging
      name: LogFilePath
      data: '{{ win19cis_public_firewall_log_path }}'
      type: string
  when:
      - win19cis_rule_9_3_7
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.3.7
      - patch
      - firewall
      - public

- name: "9.3.8 | PATCH | Ensure 'Windows Firewall: Public: Logging: Size limit (KB)' is set to '16,384 KB or greater'"
  block:
      - name: "9.3.8 | AUDIT | Ensure 'Windows Firewall: Public: Logging: Size limit (KB)' is set to '16,384 KB or greater' | Warning Check For Variable Standards."
        ansible.builtin.debug:
            msg:
                - "Warning!! You have a invalid size set for win19cis_public_firewall_log_size please read"
                - "the notes for the variable and make the necessary change to the variable to be in compliance."
        when:
            - win19cis_public_firewall_log_size < 16384

      - name: "9.3.8 | AUDIT | Ensure 'Windows Firewall: Public: Logging: Size limit (KB)' is set to '16,384 KB or greater' | Warn Count."
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: '9.3.8'
        when:
            - win19cis_public_firewall_log_size < 16384

      - name: Apply Settings To Registry."
        ansible.windows.win_regedit:
            path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging
            name: LogFileSize
            data: '{{ win19cis_public_firewall_log_size }}'
            type: dword
        when:
            - win19cis_public_firewall_log_size >= 16384
  when:
      - win19cis_rule_9_3_8
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.3.8
      - patch
      - firewall
      - public

- name: "9.3.9 | PATCH | Ensure 'Windows Firewall: Public: Logging: Log dropped packets' is set to 'Yes'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging
      name: LogDroppedPackets
      data: 1
      type: dword
  when:
      - win19cis_rule_9_3_9
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.3.9
      - patch
      - firewall
      - public

- name: "9.3.10 | PATCH | Ensure 'Windows Firewall: Public: Logging: Log successful connections' is set to 'Yes'"
  ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Policies\Microsoft\WindowsFirewall\PublicProfile\Logging
      name: LogSuccessfulConnections
      data: 1
      type: dword
  when:
      - win19cis_rule_9_3_10
  tags:
      - level1-domaincontroller
      - level1-memberserver
      - rule_9.3.10
      - patch
      - firewall
      - public
